export const sectionImages = [
  {
    header: 'Model S',
    text: 'Schedule a Demo Drive',
    buttonL: 'Custom Order',
    buttonR: 'View Inventory',
    showIcon: true,
    bgImage: '/images/model-s.jpg',
  },
  {
    header: 'Model 3',
    text: 'Schedule a Demo Drive',
    buttonL: 'Custom Order',
    buttonR: 'View Inventory',
    showIcon: false,
    bgImage: '/images/model-3.jpg',
  },
  {
    header: 'Model X',
    text: 'Schedule a Demo Drive',
    buttonL: 'Custom Order',
    buttonR: 'View Inventory',
    showIcon: false,
    bgImage: '/images/model-x.jpg',
  },
  {
    header: 'Model Y',
    text: 'Schedule a Demo Drive',
    buttonL: 'Custom Order',
    buttonR: 'View Inventory',
    showIcon: false,
    bgImage: '/images/model-y.jpg',
  },
  {
    header: 'Solar Panels',
    text: 'Lowest Cost Solar Panels in America',
    buttonL: 'Order Now',
    buttonR: 'Learn More',
    showIcon: false,
    bgImage: '/images/solar-panel.jpg',
  },
  {
    header: 'Solar Roof',
    text: 'Produce Clean Energy From Your Roof',
    buttonL: 'Order Now',
    buttonR: 'Learn More',
    showIcon: false,
    bgImage: '/images/solar-roof.jpg',
  },
  {
    header: 'Accessories',
    text: '',
    buttonL: 'Shop Now',
    showIcon: false,
    bgImage: '/images/accessories.jpg',
  },
];
